name: Deploy Static Website to S3
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: AWS-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: $ {{ secret.AWS_SECRET_ACCESS_KEY }}
        aws-region: $ {{ secret.AWS-REGION }}

    - name: Deploy to S3
      run: |
        aws s3 sync . s3://${{ secret.S3_BUCKET_NAME }} --delete --exclude ".git/*" --exclude "github/*"    
